config/routes.rb
Rails.application.routes.draw do

  devise_for :users 

resources :users do
	  resources :contacts
  end
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "index#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
 acts_as_paranoid
 belongs_to :user
end

app/models/contacts_info.rb
class ContactsInfo < ApplicationRecord

	#Contactsinfo has one user
	has_one :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  #user have so many contacts_infos
  has_many :contacts
  accepts_nested_attributes_for :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  user_contacts_path(current_user) #your path
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @user = current_user
    @contacts = @user.contacts.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @user = current_user
    @contact = @user.contacts.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @user = current_user
    @contact = @user.contacts.create(contact_params)
    
    respond_to do |format|
      if @contact.save
        format.html { redirect_to user_contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to user_contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to user_contacts_path, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @user = current_user.id
      @contact = Contact.where(user_id: @user)
      @contact = @contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :company, :address, :phone, :birthday, :user_id, :id)
    end
end

app/controllers/contacts_infos_controller.rb
class ContactsInfosController < ApplicationController
  before_action :set_contacts_info, only: [:show, :edit, :update, :destroy]

  # GET /contacts_infos
  # GET /contacts_infos.json
  def index
    @contacts_infos = ContactsInfo.all
  end

  # GET /contacts_infos/1
  # GET /contacts_infos/1.json
  def show
  end

  # GET /contacts_infos/new
  def new
    @contacts_info = ContactsInfo.new
  end

  # GET /contacts_infos/1/edit
  def edit
  end

  # POST /contacts_infos
  # POST /contacts_infos.json
  def create
    @contacts_info = ContactsInfo.new(contacts_info_params)

    respond_to do |format|
      if @contacts_info.save
        format.html { redirect_to @contacts_info, notice: 'Contacts info was successfully created.' }
        format.json { render :show, status: :created, location: @contacts_info }
      else
        format.html { render :new }
        format.json { render json: @contacts_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts_infos/1
  # PATCH/PUT /contacts_infos/1.json
  def update
    respond_to do |format|
      if @contacts_info.update(contacts_info_params)
        format.html { redirect_to @contacts_info, notice: 'Contacts info was successfully updated.' }
        format.json { render :show, status: :ok, location: @contacts_info }
      else
        format.html { render :edit }
        format.json { render json: @contacts_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts_infos/1
  # DELETE /contacts_infos/1.json
  def destroy
    @contacts_info.destroy
    respond_to do |format|
      format.html { redirect_to contacts_infos_url, notice: 'Contacts info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacts_info
      @contacts_info = ContactsInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contacts_info_params
      params.require(:contacts_info).permit(:name, :email, :phone, :address, :compay, :birthday)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def home
		if user_signed_in?
			redirect_to user_contacts_url(current_user) 
		else
			render :landaing_page
		end

	end

	def landaing_page 
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
  case flash_type
  when "success"
    "alert-success"   # Green
  when "error"
    "alert-danger"    # Red
  when "alert"
    "alert-warning"   # Yellow
  when "notice"
    "alert-info"      # Blue
  else
    flash_type.to_s
  end
end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contacts_infos_helper.rb
module ContactsInfosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/contacts/_dashbord_user_page.html.erb
<h3>list all yout contoatcs</h3>
   		<%= render partial: "contacts/index", flash: flash %> 

app/views/contacts/_edit_form.html.erb
<div class="text-center">
<%= bootstrap_form_for([@user, @contact], layout: :horizontal, :url => { :action => "update" }, label_col: "col-sm-4", control_col: "col-sm-4", class: "center-block") do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.date_select :birthday %>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
  </br>
  <%= link_to 'Destroy',  user_contact_path,  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>

<% end %>
</div>

app/views/contacts/_form.html.erb
<div class="text-center">
<%= bootstrap_form_for([@user, @user.contacts.build], layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-4", class: "center-block") do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.date_select :birthday %>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/contacts/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Birthday</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.company %></td>
        <td><%= contact.address %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.birthday %></td>
        <td><%= contact.user_id %></td>
        <td><%# link_to 'Show', contact %></td>
        <td><%# link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%# link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Contact', new_user_contact_path %>

app/views/contacts/_new_form.html.erb
<div class="text-center">
<%= bootstrap_form_for([@user, @user.contacts.build], layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-4", class: "center-block") do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.date_field :birthday %>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/contacts/edit.html.erb
<div class="text-center">
<h1>Editing Contact</h1>

<%= render 'edit_form', contact: @contact %>
</div>



<%# link_to 'Show', @contact %> |
<%# link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="row">

<div class="col-md-3 center-block">
<div class="margin-left ">
      <img class="img-responsive img-circle user_icon center-block" src="<%= asset_path('user_icon') %>" alt="">
         <ul class="nav nav-pills nav-stacked">

            <li>
              <p class="text-center center-block"><%= current_user.email %></p>
            </li>
            <li>
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
            </li>

            <li>
            <a href="">Contacts <span class="badge"><%= @user.contacts.size %></span></a>
            </li>
            <li>
            <%= menu_item "Add new Contacts", new_user_contact_path(@current_user.id) %>
            </li>
             <li>
              <%= menu_item "Log Out", destroy_user_session_path, :method => :delete %> 
           </li>
          </ul>
        </div>
</div>

<div class="center-block text-center">
<div class="col-md-8 col-xs-12">
<div class="panel panel-danger">
  <!-- Default panel contents -->
  <div class="panel-heading">CONTACTS</div>
  <!-- Table -->
  <div class="table-responsive">
<table class="table table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Address</th>
      <th>phone</th>
      <th>Age</th>
      <th>edit</th>
    </tr>
  </thead>
  <tbody>

    <% @contacts.each_with_index do |contact, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= contact.name %></td>
        <td><%= contact.email%></td>
        <td><%= contact.company %></td>
        <td><%= contact.address %></td>
        <td><%= contact.phone %></td>
        <td><%= Time.now.year - contact.birthday.year %></td>
        <td> <%= link_to 'edit', edit_user_contact_path(@user, contact), class:"btn btn-default"%></td>
      </tr>
    <% end %>

  </tbody>
</table>
</div>
<br>
</div>

</div>

</div>
</div>

app/views/contacts/new.html.erb
<div class="text-center"><h1>New Contact</h1>

<%= render 'new_form', contact: @user.contacts %>

</br>
</div>

app/views/contacts/show.html.erb
<div class="text-center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @contact.birthday %>
</p>

<%= link_to 'Back', user_contacts_path %>
</div>

app/views/contacts_infos/_form.html.erb
<%= bootstrap_form_for(contacts_info) do |f| %>
  <% if contacts_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contacts_info.errors.count, "error") %> prohibited this contacts_info from being saved:</h2>

      <ul>
      <% contacts_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :compay %>
    <%= f.text_field :compay %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_field :birthday %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts_infos/edit.html.erb
<h1>Editing Contacts Info</h1>

<%= render 'form', contacts_info: @contacts_info %>

<%= link_to 'Show', @contacts_info %> |
<%= link_to 'Back', contacts_infos_path %>

app/views/contacts_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts Infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Compay</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts_infos.each do |contacts_info| %>
      <tr>
        <td><%= contacts_info.name %></td>
        <td><%= contacts_info.email %></td>
        <td><%= contacts_info.phone %></td>
        <td><%= contacts_info.address %></td>
        <td><%= contacts_info.compay %></td>
        <td><%= contacts_info.birthday %></td>
        <td><%= link_to 'Show', contacts_info %></td>
        <td><%= link_to 'Edit', edit_contacts_info_path(contacts_info) %></td>
        <td><%= link_to 'Destroy', contacts_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contacts Info', new_contacts_info_path %>

app/views/contacts_infos/new.html.erb
<h1>New Contacts Info</h1>

<%= render 'form', contacts_info: @contacts_info %>

<%= link_to 'Back', contacts_infos_path %>

app/views/contacts_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contacts_info.name %>
</p>

<p>
  <strong>:</strong>
  <%= @contacts_info.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contacts_info.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contacts_info.address %>
</p>

<p>
  <strong>Compay:</strong>
  <%= @contacts_info.compay %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @contacts_info.birthday %>
</p>

<%= link_to 'Edit', edit_contacts_info_path(@contacts_info) %> |
<%= link_to 'Back', contacts_infos_path %>

app/views/index/_landaing_page.html.erb
<h1>Welocme to Contact app</h1>
<h3>here you can creat and mange all your contonac info be useing this app</h3>
<h3>you only need to Sing Up to start useing this app</h3>
<button class="btn"><%= link_to "Sing Up", new_user_registration_path %></button> <br>
<button class="btn"><%= link_to "hoem", root_path %></button>

app/views/index/landaing_page.html.erb
    <!-- Header -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                <div class="col-lg-12">
                    <img class="img-responsive" src="<%= asset_path('profile') %>" alt="">
                    <div class="intro-text">
                        <h1 class="name">Contacts App</h1>
                        <hr class="star-light">
                        <span class="skills">web copy for yoru contacts info</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Portfolio Grid Section -->
    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>You Can</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row text-center">
                <div class="col-sm-4 portfolio-item">
                        <img src="<%= asset_path('portfolio/cloud-computing')%>" class="img-responsive center-block" alt="Cabin">
                    <p>access from anywhere and anytime</p>
                </div>
              <div class="col-sm-4 portfolio-item">
                        <img src="<%= asset_path('portfolio/keywords')%>" class="img-responsive center-block" alt="Cabin">
                    <p>everything it's up and protected for your info</p>
                </div>
               <div class="col-sm-4 portfolio-item">
                        <img src="<%= asset_path('portfolio/medal')%>" class="img-responsive center-block" alt="Cabin">
                    <p>all of the is for free</p>
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>this a test app done for JungleCoders, in this app you cand sing up and use this app. this exstr text you can edite later. this text you can change it later, </p>
                </div>
                <div class="col-lg-4">
                    <p>this text you can change it later, this text you can change it later, this text you can change it later, this text you can change it later. </p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                <%= menu_item "Sing Up", new_user_registration_path, class: "btn btn-lg btn-outline fa fa-download" %> 
                </div>
            </div>
        </div>
    </section>

app/views/index/user_contacts.html.erb
<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Birthday</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.company %></td>
        <td><%= contact.address %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.birthday %></td>
        <td><%= contact.user_id %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Contact', new_user_contact_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Contacts App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag    'freelancer.min', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


       <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
<body id="page-top" class="index">
<div id="skipnav"><a href="#maincontent">Skip to main content</a></div>

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <% if current_user %>
                <%=link_to "Contacts App", user_contacts_path(@current_user.id), class: "navbar-brand"%>
                    <% else %>
                <%=link_to "Contacts App", root_path, class: "navbar-brand"%>
                <% end %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                           <% if current_user %>
       <p class="navbar-text"><%= current_user.email %></p>
               <%= menu_item "Log Out", destroy_user_session_path, :method => :delete %>
    <% else %>
                 <%= menu_item "Sing Up", new_user_registration_path %>

             <%= menu_item "Log in", new_user_session_path %>


        <% end %>
                 
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>



<div class="margin-top">
<%= render partial: "shared/flash_messages", flash: flash %> 

    <%= yield %>
 </div>    
        <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>3481 Melrose Place
                            <br>Beverly Hills, CA 90210</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Facebook</span><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Google Plus</span><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Twitter</span><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Linked In</span><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Dribble</span><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Freelancer</h3>
                        <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Your Website 2016
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>


    <!-- Theme JavaScript -->
    <%= javascript_include_tag 'freelancer.min', 'data-turbolinks-track': 'reload' %>
     <!-- jQuery -->
    <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap Core JavaScript -->
        <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track': 'reload' %>

  </body>

</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>

app/views/shared/_landaing_page.html.erb
<h1>Welocme to Contact app</h1>
<h3>here you can creat and mange all your contonac info be useing this app</h3>
<h3>you only need to Sing Up to start useing this app</h3>
<%= link_to "Sing Up", new_user_registration_path %>
<%= link_to "hoem", root_path %>